### ISSUE TITLE
Person Following

### ISSUE THREAD

**Issue by jws-1** [LASR-at-Home/Base#173]
- [ ] #172 for person tracking
 - [ ] In mapped areas
 - [ ] In unmapped areas
